#PBS -lwalltime=48:00:00
#PBS -lselect=1:ncpus=1:mem=8gb:ngpus=1:gpu_type=P100

module load anaconda3/personal

mkdir model
mkdir tensorboard
mkdir data

cp $WORK/Msc_project/neural_sum/exp1/try1_gpu/data/* $TMPDIR/data/
cp $WORK/Msc_project/neural_sum/exp1/try1_gpu/model/* $TMPDIR/model/


python3 $HOME/MSc_project/neural_sum_1/code/Tensorflow_network/run_cx1.py $WORK/Msc_project/neural_sum/exp1/data/ $TMPDIR/data/ $TMPDIR/ > output.txt

cp -r * $WORK/Msc_project/neural_sum/exp1/try1_gpu/